name: Autorelease

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-24.04
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - name: Run updaters
        run: |
          npm install
          mise codegen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        with:
          commit-message: "Updater: stuff changed"
          branch: updater-bot
          delete-branch: true
          title: "Updater: stuff changed"
          body: "Changes from update scripts."
          reviewers: lucasew

  build:
    name: Build on PR
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with: { fetch-depth: 0 }
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - run: npm install
      - run: mise codegen
      - name: Build
        run: hugo --minify --baseURL "https://lucasew.github.io"

  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with: { fetch-depth: 0 }
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
      - run: npm install
      - run: mise codegen
      - name: Build
        run: hugo --minify --baseURL "https://lucasew.github.io"
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with: { path: ./public }
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
